### ISSUE TITLE
Remove use of Joda Time

### ISSUE THREAD

**Issue by edalex-ian** [apereo/openEQUELLA#1022]
Java 8+ projects are recommended by the Joda project to convert to using the matching features no in `java.time`:

> The standard date and time classes prior to Java SE 8 are poor. By tackling this problem head-on, Joda-Time became the de facto standard date and time library for Java prior to Java SE 8. **Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.**

From: https://www.joda.org/joda-time/

**Describe the solution you'd like**

Remove the joda-time dependency, and then update code to use the new `java.time` classes.

**Comment by PenghaiZhang** [comment]
We currently have a few files using Joda Time. 
Links to these files:
https://github.com/apereo/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java#L50

https://github.com/apereo/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeAttachmentSerializer.java#L59

https://github.com/apereo/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/src/com/tle/web/echo/EchoUtils.java#L55
