### ISSUE TITLE
New UI: Unable to accept CAL/CLA licencing agreement

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#1091]
**Describe the bug**
Accepting an agreement doesn't work if you click to the link to the portion via the holding item it's linked to. Can't see any errors in the javascript console or openEquella logs

**To Reproduce**

1. Ensure you have the new ui enabled
2. Create/publish item in the Books or Journals collection
3. Create an item in the eReserve articles collection, and link it to the Books item you created
4. Go to the item summary page for the item that you created in step 2
5. In the copyright panel, click Activate, and follow the prompts
6. Once the attachment has been activated, click the attachment link
![Capture](https://user-images.githubusercontent.com/4625498/60639774-66801180-9e67-11e9-9776-7d46479b375b.PNG)
7. In the Copyright agreement dialog that appears, try to click the green Accept button

**Expected behavior**
Clicking the accept button should display the attachment

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: 2019.1
- OS: WIndows
- Browser Chrome

**Comment by edalex-ian** [comment]
This was fixed and tested yeah @mrblippy ?

**Comment by mrblippy** [comment]
Oops, i missed this one. Yep, the Accept button now works

@
