### ISSUE TITLE
Moderators have to click Save/Edit resource twice to go to right pages

### ISSUE THREAD

**Issue by PenghaiZhang** [apereo/openEQUELLA#1111]
**Describe the bug**
In RC, when moderating items, if moderators are editing an item, they will have to click Save twice in order to view the right page.

Please note this bug was fixed before in PR #781 
@SammyIsConfused may be more familiar with this issue. 

**To Reproduce**

1. Select a task to moderate
2. Click on Edit resource
3. Make changes on the item
4. Click on Save

**Expected behavior**
The Save button should disappear and another four buttons should come up

**Screenshots**
![Screenshot from 2019-07-15 12-00-28](https://user-images.githubusercontent.com/47203811/61192534-4e768080-a6f8-11e9-96c6-f42e323f7376.png)

**Stacktrace**
None

**Platform:**

- OpenEquella Version: 2019.1
- OS: Ubuntu 18.04
- Browser Chrome

**Additional context**

**Comment by cathfitz** [comment]
Fixed
