### ISSUE TITLE
Unable to build installer using **sbt**

### ISSUE THREAD

**Issue by abdkhanEummena** [apereo/openEQUELLA#1168]
Unable to build installer using **sbt**

1. Clone openEquella in your machine.
2. Try running `sbt installerZip`.

sbt should work just fine and build the openEquella installer.

![image](https://user-images.githubusercontent.com/53985295/62828463-a1166000-bc04-11e9-9704-a53e1d1b44ac.png)

[error] java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /equella/dev/equella/autotest/Interface/Tests/src/com/tle/resttests/util/files/Special characters - ?????? test2.jpg
[error] 	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
[error] 	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
[error] 	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
[error] 	at java.io.File.toPath(File.java:2234)
[error] 	at sbt.io.IO$.relativize(IO.scala:612)
[error] 	at sbt.io.Mapper.$anonfun$rebase$4(PathMapper.scala:90)
[error] 	at sbt.io.IOSyntax0$$anon$1.$anonfun$$bar$1(syntax.scala:13)
[error] 	at sbt.io.PathFinder.$anonfun$pair$1(Path.scala:360)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at sbt.io.PathFinder.pair(Path.scala:360)
[error] 	at sbt.io.IO$.copyDirectory(IO.scala:684)
[error] 	at sbt.io.IO$.copyDirectory(IO.scala:674)
[error] 	at sbt.io.IO$.copyDirectory(IO.scala:657)
[error] 	at sbt.Resolvers$.$anonfun$local$3(Resolvers.scala:34)
[error] 	at sbt.Resolvers$.creates(Resolvers.scala:148)
[error] 	at sbt.Resolvers$.$anonfun$local$2(Resolvers.scala:34)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$2(BuildLoader.scala:154)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$1(BuildLoader.scala:153)
[error] 	at sbt.internal.MultiHandler.apply(BuildLoader.scala:26)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:222)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:253)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /equella/dev/equella/autotest/Interface/Tests/src/com/tle/resttests/util/files/Special characters - ?????? test2.jpg
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

**Platform:**
- jdk: [Oracle 1.8.0_221]
- OpenEquella Version: [master branch]
- OS: Ubuntu 16.04

**Comment by edalex-ian** [comment]
Heya @abdkhanEummena 

Interesting this is failing for you. We've not seen this issue before, and indeed that command is one that out CI builds run so we're confident it works.

However, what has grabbed my attention is that it's failing for you when reading one of the 'special character' files used for testing support of filenames with unicode characters in them. Here is a screenshot which shows the filenames on my machine:

![2019-08-12-090958_459x92_scrot](https://user-images.githubusercontent.com/43919233/62840634-3e46c680-bce1-11e9-8294-7defcab8b673.png)

So it feels like maybe your machine is having an issue with unicode files. Maybe do an `ls -1 /equella/dev/equella/autotest/Interface/Tests/src/com/tle/resttests/util/files/` and see how that group of files compare to the above screenshot.

Also, are you trying to compile the installer as a step to doing some dev work, or did you just want a copy of the installer?

Cheers.

**Comment by abdkhanEummena** [comment]
Upon further research I realized the **LC_ALL** locale wasn't set and setting it worked for me.
![image](https://user-images.githubusercontent.com/53985295/62934395-1723ee00-bde2-11e9-8e38-958f9c61c223.png)

How to set the locale 
- export LANG="en_US.UTF-8"
- export LC_ALL="en_US.UTF-8"

**Comment by abdkhanEummena** [comment]
Upon further research I realized the **LC_ALL** locale wasn't set and setting it worked for me.

![image](https://user-images.githubusercontent.com/53985295/62934662-c3fe6b00-bde2-11e9-8bae-e2ea9108b4e4.png)


How to set the locale 
- export LANG="en_US.UTF-8"
- export LC_ALL="en_US.UTF-8"

**Comment by edalex-ian** [comment]
Excellent, great to hear you've got it sorted @abdkhanEummena . :+1:
