### ISSUE TITLE
Collection dropdown isn't correct width

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#628]
**Describe the bug**
The collection dropdown appears in the middle of the input field, and doesn't take up the full width. Happens in old and new ui, but it's more annoying in the new ui.

**To Reproduce**
1. Ensure that the new search page isn't enabled
2. Go to a page that has a search dropdown (eg. search, manage resources)
3. Click on the 'Within all resources' dropdown

**Expected behavior**
![capture](https://user-images.githubusercontent.com/4625498/49192196-1cfdae80-f3ce-11e8-8b2f-3a8b41160d97.PNG)

**Screenshots**
![capture](https://user-images.githubusercontent.com/4625498/49192168-07888480-f3ce-11e8-8348-4bbffb77df93.PNG)

**Platform:**
 - OpenEquella Version: 6.6, 2018.2
 - OS: Windows 10
 - Browser: Chrome

**Comment by SammyIsConfused** [comment]
This also seems to occur on the search page drop down.
![screenshot_2018-12-03 search equella](https://user-images.githubusercontent.com/24543345/49351746-f959a180-f708-11e8-9295-635b68b1eea1.png)

**Comment by abidingotter** [comment]
I tested normal search page and Manage Resources page in IE11, Chrome, and Edge.  When the screen is too narrow the sections (Collections, Advanced Searches, Remote Repositories) stack below each other.
