### ISSUE TITLE
New LTI attachments always have a blank name

### ISSUE THREAD

**Issue by doolse** [apereo/openEQUELLA#679]
**Describe the bug**
When you create a new "External tool provider (LTI)" attachment, clicking add gives you a blank attachment. It used to go to "attachment details editor" which would have a default description and let you edit it but now that we bypass that page because of #520, you don't get an attachment name at all.

**To Reproduce**
1. Go to a contribution wizard which has an attachment control which allows LTI attachments
2. Create a valid LTI attachment and click Add
3. Returns back to the wizard and gives you a blank attachment entry

**Expected behavior**
It should give you a default name for the attachment.

**Screenshots**
![image](https://user-images.githubusercontent.com/2178038/50465433-723bd880-09eb-11e9-8d32-793d16cbd9d3.png)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**
 - OpenEquella Version: 2018.2

**Additional context**
Autotest which found this - *LTIAttachmentControlTest*

**Comment by edalex-ian** [comment]
Heya @mrblippy 

Could you please test on 2019.1 and 2018.2. If all good, please close.

IS

**Comment by mrblippy** [comment]
Verified in 2018.2 and 2019.1
