### ISSUE TITLE
search API docs - generic references to "SOAP where clause" could be improved

### ISSUE THREAD

**Issue by phette23** [apereo/openEQUELLA#730]
In a few places in the search REST API documentation there's some text about the "where" clause used to query items:

> The where-clause in the same format as the old SOAP one. See https://equella.github.io/

This isn't useful if a) you don't know what the old SOAP clause was like or b) you do know but you've forgotten or need specific details. The link to oE's docs site is helpful but is several steps away from anything actually telling you how to format the clause. I believe the closest link to pertinent information is here: https://equella.github.io/guides/RestAPIGuide.html#searching

This "where-clause" text appears in three files that I can find: https://github.com/equella/Equella/search?q=%22where-clause%22&unscoped_q=%22where-clause%22

I propose at least updating the URL to be more useful and perhaps removing the SOAP reference, which is unhelpful (if you know about the SOAP where clause, then you probably assume this "where" is the same; if you don't know about it, then this information isn't useful). This is what I'd write instead:

> For details on structuring the where clause see https://equella.github.io/guides/RestAPIGuide.html#searching

I signed the online CLA with Apereo just now and if that text looks good I can submit a simple string fix PR for the aforementioned files.

**Comment by edalex-ian** [comment]
Heya @phette23 ,

That's great to hear you've signed the CLA. We'd definitely welcome any PRs you're able to offer. Please just have a quick read of the CONTRIBUTING.md, and then go for it.

Thanks in advance! :)

**Comment by edalex-ian** [comment]
Heya @mrblippy 

Could you please test?

Thanks! :+1:

**Comment by mrblippy** [comment]
Hi Eric, since you committed this change the link to the openEQUELLA docs changed (when we moved over to the apereo github organisation)
Can you change the links to be https://apereo.github.io/openEQUELLA-docs/

**Comment by cbeach47** [comment]
@phette23 - Hi Eric, we'd like to fold this into the main repo by EOD Thursday (US).  Could you make the change @mrblippy noted and open a PR please?

**Comment by mrblippy** [comment]
Sorry, i missed the last response. Doing the pull request now

**Comment by phette23** [comment]
Sorry I've been on vacation and just saw this now. Looks like it's all set?

**Comment by mrblippy** [comment]
Yep, all good eric
