### ISSUE TITLE
Failing to publish a new item

### ISSUE THREAD

**Issue by PenghaiZhang** [apereo/openEQUELLA#780]
**Describe the bug**
This bug occurs only in new UI.
Users cannot publish a new item even though all mandatory fields have been filled in.

**To Reproduce**

**To test the first bug,** 
1. Import the scheme and collections attached to this issue
[Collection.Definition.-.TEST.of.wizard.zip](https://github.com/equella/Equella/files/2969551/Collection.Definition.-.TEST.of.wizard.zip)
[Schema.-.Test.of.wizard.schema.zip](https://github.com/equella/Equella/files/2969552/Schema.-.Test.of.wizard.schema.zip)

2. Open up a contribution,
3. Visit page 2,   
4. Visit page 1,
5. Fill in the field of Item name,
6. Click save and then click complete wizard,
7. Select either option displayed in page 2,
8. Click save again

**Expected behavior**
Users are asked to complete wizard again.

**Screenshots**
![Screenshot from 2019-03-15 11-00-48](https://user-images.githubusercontent.com/47203811/54410357-3b9a7200-473f-11e9-86eb-947d38dc59a8.png)
![Screenshot from 2019-03-15 11-01-04](https://user-images.githubusercontent.com/47203811/54410358-3c330880-473f-11e9-88cf-20444ab30e54.png)

OpenEquella Version: 6.6, 2018.2
OS: Ubuntu
Browser Chrome

**Comment by cathfitz** [comment]
Tested and all working as expected

**Comment by cathfitz** [comment]
May need to be backported

**Comment by SammyIsConfused** [comment]
Backported to 2018.2.

**Comment by edalex-ian** [comment]
@cathfitz could you please confirm whether the backport works and if so close?

**Comment by cathfitz** [comment]
Backport confirmed as working in stabledev.
