### ISSUE TITLE
Provide JNLP alternative for Admin Console

### ISSUE THREAD

**Issue by edalex-ian** [apereo/openEQUELLA#783]
**Is your feature request related to a problem? Please describe.**

Currently the primary way openEQUELLA (oEQ) Administrators access the oEQ Administration Console (Admin Console) is via a link to a JNLP file provided by the Settings section of oEQ. Clicking this link downloads and launches the Java Web Start oEQ Admin Console - assuming Java Web Start is installed on the user’s machine.

However with Oracle’s deprecation and subsequent removal of JNLP, a solution needs to be provided to support use of the Admin Console while work is done to migrate its functionality to the web UI.

**Describe the solution you'd like**

Just like we provide downloadable packages for the oEQ Server (installer and upgrade package), we will provide a download package of the admin console each time a new version is released. Users or their organisation will then need to download this and install it on their workstation(s). The install may initially be a simple process of extracting an archive to a chosen directory. (Later, resourcing permitting, we could look at doing an installer - or we can focus that energy on putting the functionality into the New UI.)

Now having installed the Admin Console on their workstation they will execute (e.g. by double clicking) a batch file/shell script/other which will start the Admin Console. Following which, initially they will need to specify the details for their server (i.e. URL), following which they’ll need to enter their user credentials. (On subsequent uses, they’ll simply choose their server from a drop down list - or go with the default if they only have one.)

(At a technical level - see below - this will actually start with a call to the oEQ server to download the reciprocal Admin Console code, and then launch it.)

Following successful launching of the Admin Console, users will continue to use it the same as they currently do.

**Additional context**

Although this issue is being raised here, there is the intention to build this in  a separate repo (e.g. `equella/admin-console-package`).

The implementation of this package should consist of:

* The JRE - a common approach to migrating from JNLP to a stand-alone app
* A Java Swing launcher that will prompt for servers (storing a list, and last used), then download the Admin Console core from the oEQ instance (to ensure they're bytecode compatible) or use a local cached version, then spawn the Admin Console
* Operating specific launch scripts - to use the packaged JRE to launch the Java Swing app

Seeing there is an OS specific element here, three packages will be provided - Windows, macOS and Linux.

OpenJDKs / JREs can be downloaded from:

* https://jdk.java.net/11/
  * There are known issues using the admin console with Java 10 and above (e.g. #600), so we may require older ones: https://jdk.java.net/archive/
* https://adoptopenjdk.net/
  * Possibly the preferred option

On packaging the JDK / JRE there are many sources of information on the web. And also note there are command line tools etc. for producing a native Java application package - both in the JDK and in IDEs.

**Comment by cbeach47** [comment]
:+1:

**Comment by edalex-ian** [comment]
Note: The launcher project can be found over at https://github.com/equella/admin-console-package/

**Comment by mrblippy** [comment]
Verified, the beta release is located here https://github.com/apereo/openEQUELLA-admin-console-package/releases
