### ISSUE TITLE
Broken blackboard language strings

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#784]
**Describe the bug**
???com.tle.core.connectors.blackboard.error.accessdenied???
???com.tle.core.connectors.blackboard.proxytool.description???
???com.tle.core.connectors.blackboard.finduses.showarchived.courses???
???com.tle.core.connectors.blackboard.finduses.course???
???com.tle.core.connectors.blackboard.finduses.location???

Located on Settings>External system connectors>Create new connector 
![Capture](https://user-images.githubusercontent.com/4625498/54577546-56772a00-4a50-11e9-837e-50f5284a4fcf.PNG)

Also a missing language string in the building block
![Capture](https://user-images.githubusercontent.com/4625498/54578223-0baae180-4a53-11e9-86fd-2ba6660ed3a1.PNG)

Find uses page
![Capture](https://user-images.githubusercontent.com/4625498/54581247-eec8db00-4a5f-11e9-9ea1-a06d2e2421b4.PNG)

**Platform:**

- OpenEquella Version: 2018.2, 2019.1
- OS: windows 10
- Browser chrome

**Comment by edalex-ian** [comment]
Heya @cbeach47 

I note you added it to 2019.1, so I thought I'd assign across to you.

Cheers.

**Comment by cbeach47** [comment]
Merged into `develop` and cherry-picked into `release/2019.1`

@mrblippy - before we close this, do you have a minute to do a sanity test on the 'accessdenied' broken string?  I replicated the broken string yesterday, and it no longer shows up, but in my final testing before closing out this issue, while I can make properly formatted errors to appear, I can't get the 'Access denied' wording to appear.  Interested if you can in your local Bb setup.
