### ISSUE TITLE
Cant make scorm/ims packages regular zip packages when dragging and dropping

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#791]
**Describe the bug**
When adding a content package (scorm, ims or qti) by clicking 'add a resource' you are given a choice what you want the file to be treated as
![Capture](https://user-images.githubusercontent.com/4625498/54887533-2fa17380-4ee8-11e9-8635-d04b475ec99d.PNG)

But when dragging and dropping the same content package you aren't given that option
[Uploading ContentPackagingSingleSCO_SCORM12 (1).zip…]()
![Capture](https://user-images.githubusercontent.com/4625498/54887634-8491b980-4ee9-11e9-9518-8704c9d84da0.PNG)

Also have a look at this video for a demonstration
https://drive.google.com/file/d/1_AFCFL1gg0sDdNgL2-b3OxARE1DnuMr0/view?usp=sharing

**Expected behavior**
After dragging and dropping a scorm, ims or qti package users should be able to edit the attachment, and choose what they want the file to be treated as inside openEQUELLA

**Screenshots**

**Platform:**

- OpenEquella Version: 6.6, 2018.2, 2019.1

**Comment by cathfitz** [comment]
The options to treat a zip file in a way other than its current designation is part of the upload wizard process, not designed to be changed once the file has been uploaded. Users would need to use the upload wizard and not drag and drop to get this option, as the idea of the drag and drop option is to avoid the longer wizard process.
