### ISSUE TITLE
Settings Page broke in IE 11

### ISSUE THREAD

**Issue by timrattle** [apereo/openEQUELLA#792]
In 2018.2 in IE 11 if you go to the Settings page you will see a blank canvas. The browser console shows the following error 

<img width="1090" alt="Screen Shot 2019-03-25 at 11 27 57 am" src="https://user-images.githubusercontent.com/48897934/54891936-80729580-4f03-11e9-9815-ef164a523ee1.png">

**Comment by mrblippy** [comment]
The new UI also doesn't work in ie11. I remember some polyfills had to be done to get the new UI working for ie11 in 6.6

Not sure why it's broken again in 2018.2 and 2019.1

**Comment by cathfitz** [comment]
Fixed along with a number of other issues in IE11 UI
