### ISSUE TITLE
openEQUELLA resource selector not functioning inside new ui

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#805]
**Describe the bug**
The return selections button doesn't actually return your selections. And there is no way to close the iframe. (see attached video). This problem seems to be specific to 2019.1
https://drive.google.com/open?id=1RMUM9JJI-i0X7AnVzSbwev4moOOuBsFp

**To Reproduce**

1. Import the attached schema and collection
2. Start a contribution using the collection you imported
3. Click 'Add a resource' to open up a selection session, and perform a search
4. Click on a blue select button to to select one of the results
5. Click the return selection button
6. Your selection wont actually get sent, and the only way to exit the selection session is to refresh the page

**Expected behavior**
Clicking return selections should return the selections, as well as closing the iframe. Also, the close button at the top right should close the iframe

**Platform:**

- OpenEquella Version: 2019.1

**Comment by doolse** [comment]
This might be related to #721 being merged in (selection session stuff) but then abondoning it

**Comment by edalex-ian** [comment]
This is pretty broken, so we'll need it fixed for 2019.1.

**Comment by cathfitz** [comment]
Tested and all seems to be fixed.
