### ISSUE TITLE
Add UI Settings as a target in the Security Manager under the System Settings entry

### ISSUE THREAD

**Issue by cathfitz** [apereo/openEQUELLA#809]
The new UI settings accessed from the Settings page currently falls under the top level System Settings entry in the Security Manager. So if the EDIT_SYSTEM_SETTINGS permission is granted for a user, they will see the UI settings in the menu.
A target needs to be added in the System Settings list for UI Settings so that permissions can be granted or revoked against that target.

**Comment by edalex-ian** [comment]
This has been done, and is in 2019.1.
