### ISSUE TITLE
Flikr Attachment control bug

### ISSUE THREAD

**Issue by carl-edalex** [apereo/openEQUELLA#824]
**Describe the bug**
When an attachment control is restricted to Flikr and a user chooses "Save and Continue", they are presented with an error similar to this:

No tree for id:p0c4_dialog_fh

Note:  the _p0c4_ part of the error refers to the div id of that control in the contribution wizard.

**To Reproduce**

Set a collection up to have an attachment control that is restricted strictly to Flikr.  The other configuration isn't important.  

Perform a contribution, clicking on "Save and continue".  The error will render.

**Expected behavior**
The save and continue should just show the green "saved" confirmation in the contribution wizard without any error, leaving the user in the same contribution wizard.

**Platform:**

- OpenEquella Version: 2018.2 only.  I've tested in  6.5 and 6.6 and was unable to reproduce
- OS: n/a
- Browser n/a

**Comment by carl-edalex** [comment]
Sorry - here is a stack trace:

<tr><td bgcolor="#993300" style="color:White; font-size : xx-small;" colspan="5">com.tle.web.sections.NoTreeForIdException: No tree for id:pc4_dialog_fh
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.getTreeForId(DefaultSectionInfo.java:138)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.getTreeForId(DefaultSectionInfo.java:411)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.getSectionForId(DefaultSectionInfo.java:789)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:533)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.removeTree(DefaultSectionInfo.java:425)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.wizard.WebWizardPage.removeTrees(WebWizardPage.java:364)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.wizard.command.SaveAndContinue.execute(SaveAndContinue.java:68)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.wizard.section.WizardBodySection.command(WizardBodySection.java:210)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at sun.reflect.GeneratedMethodAccessor814.invoke(Unknown Source)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.lang.reflect.Method.invoke(Method.java:498)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:100)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:95)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:500)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:469)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:462)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.registry.AbstractSectionsController.execute(AbstractSectionsController.java:49)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:73)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:53)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
<br>&nbsp;&nbsp;&nbsp;&nbsp;    at java.lang.Thread.run(Thread.java:748)

**Comment by edalex-ian** [comment]
We'll look to address in 2019.1, and we'll backport to 2018.2.

**Comment by cathfitz** [comment]
Fixed
