### ISSUE TITLE
New UI: Allow for customization of item summary page titles

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#838]
**Is your feature request related to a problem? Please describe.**
In the old openEQUELLA UI all Resource summary pages have the text 'Resource summary' text in the banner (which can be customized via a language string).
![Capture](https://user-images.githubusercontent.com/4625498/56263421-36f22080-6126-11e9-9d40-611c2da343f1.PNG)

When the new ui is enabled the top bar always displays the item name, it can't be customized at all
![Capture2](https://user-images.githubusercontent.com/4625498/56263437-3ce80180-6126-11e9-9865-6c2da002950d.PNG)

In the past at least one client (swinburne) used to change the 'Resource summary' text to instead say 'Swinburne Research Bank' (the name of their openEQUELLA instance). 
From the client

'As an open access repository, most of our users don’t use the internal Equella search interface to find content. Instead they access our records directly via Google or some other external search engine.

So when you access this record on the old UI, you can see that ‘Swinburne Research Bank’ is in bold at the top of the page, and thus, you can see the context of where you have landed'

**Describe the solution you'd like**
There are two potential options for fixing this

Option 1: In the new UI, make the heading text be a language string instead of the item name

Option 2: Provide some sort of UI to enable admins to specify what heading appears at the top of each page

**Comment by edalex-ian** [comment]
All done, closing.
