### ISSUE TITLE
REST API for easier editing of attachments / metadata

### ISSUE THREAD

**Issue by doolse** [apereo/openEQUELLA#873]
The new cloud provider control functionality added an API for doing the following while the wizard is open:
* Edit the XML metadata
* Add/Edit/Delete attachment(s) and manipulate their associated XML metadata node

It would be good if the existing Item REST APIs also had access to this same functionality. It should be located at:
`PUT /api/item/<UUID>/<version>/edit`

**Comment by edalex-ian** [comment]
This is one of the items listed in #760
