### ISSUE TITLE
New UI: Logo not displaying on login page

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#953]
**Describe the bug**
It seems like something that clients would want displayed on the login screen, since that will be most user's first interaction with the system.

**To Reproduce**

1. Enable the new ui
2. Logout
3. Notice that the logo isn't there

**Expected behavior**
Logo should be displayed on login page

**Screenshots**
![Capture](https://user-images.githubusercontent.com/4625498/58455567-65bbd780-8165-11e9-89e5-0c7e3502157e.PNG)

**Platform:**

- OpenEquella Version: 2018.2, 2019.1
- OS: windows 10
- Browser: chrome

**Comment by cathfitz** [comment]
Fix different for 2018.2 - created new Jira ticket for Jolse to fix.

**Comment by cathfitz** [comment]
Fixed in 2019.1 and 2018.2
